# It is shared between includes anyway
stages:
  - build
  - test
  - deploy
  - cleanup
default:
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure
      - runner_unsupported
      - stale_schedule
      - job_execution_timeout
      - unmet_prerequisites
      - scheduler_failure
      - data_integrity_failure
variables:
  TAG_NAME: ${CI_COMMIT_REF_SLUG}
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}/back
  IMAGE_WITH_TAG: ${IMAGE_NAME}:${TAG_NAME}
  FRONT_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/front
  FRONT_IMAGE_WITH_TAG: ${FRONT_IMAGE_NAME}:${TAG_NAME}
  DEPLOYMENT_PATH: /tcm_deployment/${CI_PROJECT_NAME}
  DEPLOYMENT_IP: 13.38.93.123

include:
  - local: gitlab-ci/gitlab-ci-merge-request.yml
  - local: gitlab-ci/gitlab-ci-tags-prod.yml
  - local: gitlab-ci/gitlab-ci-branch-main.yml
  #    rules:
  #    - if: $CI_COMMIT_TAG =~ /^[0-9]+.[0-9]+.[0-9]+$/
