# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.url.base: "%env(APP_URL)%"
   # app.url.webapp: "%env(APP_URL_WEBAPP)%"
    # OUR APP
    app.sso.serviceprovider.x509cert: "%env(APP_SSO_SERVICEPROVIDER_X509CERT)%"
    app.sso.serviceprovider.privateKey: "%env(APP_SSO_SERVICEPROVIDER_PRIVATEKEY)%"
    # THE SSO APP
    app.sso.identityprovider.x509cert: "%env(APP_SSO_IDENTITYPROVIDER_X509CERT)%"
    app.sso.identityprovider.entityId: "%env(APP_SSO_IDENTITYPROVIDER_ENTITYID)%"
    app.sso.identityprovider.loginurl: "%env(APP_SSO_IDENTITYPROVIDER_LOGINURL)%"
    app.sso.identityprovider.logouturl: "%env(APP_SSO_IDENTITYPROVIDER_LOGOUTURL)%"
    app.sso.configuration:
        strict: true
        debug: true
        sp:
            entityId: '%app.url.base%'
            assertionConsumerService: { url: '%app.url.base%/authentication' }
            singleLogoutService: { url: "%app.url.base%/api/1.0/login/sso/saml2/logout" }
            NameIDFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
            x509cert: "%app.sso.serviceprovider.x509cert%"
            privateKey: "%app.sso.serviceprovider.privateKey%"
        idp:
            entityId: "%app.sso.identityprovider.entityId%"
            singleSignOnService: { url: "%app.sso.identityprovider.loginurl%" }
            singleLogoutService: { url: "%app.sso.identityprovider.logouturl%" }
            x509cert: "%app.sso.identityprovider.x509cert%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Authenticator\Saml2Authenticator:
        class: App\Authenticator\Saml2Authenticator
        arguments:
            $checkPath: 'api_login'


    OneLogin\Saml2\Auth:
        class: OneLogin\Saml2\Auth
        arguments:
            $settings: "%app.sso.configuration%"